name: Pre-commit Checks and Tests

on:
  push:

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files